
../build/whiskit_gui \
--DIST 0.07 \
--CPITCH -89 \
--NO_MASS 0 \
--CYAW 0 \
--BLOW 3 \
--DEBUG 0 \
--OBJECT 1 \
--SPEED 400 \
--ACTIVE 1 \
--TIME_STOP 120 \
--WHISKER_NAMES RA0 RB0 LA0 LB0 \
--PITCH 0 \
--AMP_BWD 15 \
--AMP_FWD 30 \
--WHISK_FREQ 8. \
--SAVE_VIDEO 0 \
--SAVE 1 \
--file_video "../output/video_peg.mp4" \
--dir_out ../output/full_array_peg