../build/whiskit_gui \
--MODEL_TYPE 1 \
--CDIST 50 \
--CPITCH -89 \
--CYAW 90 \
--DEBUG 0 \
--OBJECT 1 \
--TIME_STOP 0.25 \
--ACTIVE 1 \
--WHISKER_NAMES R \
--SAVE_VIDEO 0 \
--SAVE 1 \
--file_video "../output/video_peg.mp4" \
--dir_out ../output/full_array_peg_active