../build/whiskit_gui \
--MODEL_TYPE 1 \
--CDIST 50 \
--CPITCH -89 \
--NO_MASS 0 \
--CYAW 90 \
--BLOW 1 \
--DEBUG 0 \
--OBJECT 1 \
--SPEED 0 \
--TIME_STOP 1. \
--ACTIVE 1 \
--WHISKER_NAMES R \
--PEG_LOC 0 20 0 \
--SAVE_VIDEO 0 \
--SAVE 1 \
--file_video "../output/video_peg.mp4" \
--dir_out "/media/nadina/Nadina's Soul1/__projects/01_Dynamo/01_datasets/simulation_examples/whiskit_output/whiskit_peg_active_8x_new"