../build/whiskit_gui \
--MODEL_TYPE 1 \
--CDIST 50 \
--CPITCH -89 \
--NO_MASS 0 \
--CYAW 90 \
--BLOW 1 \
--DEBUG 0 \
--OBJECT 0 \
--SPEED 0 \
--TIME_STOP 0.5 \
--ACTIVE 1 \
--WHISKER_NAMES R \
--SAVE_VIDEO 0 \
--SAVE 1 \
--file_video "../output/video_peg.mp4" \
--dir_out ../output/full_array_noncontact_active_graphics