
../build/AppWhiskerGui \
--DIST 0.07 \
--CPITCH -89 \
--CYAW 0 \
--BLOW 3 \
--DEBUG 0 \
--OBJECT 0 \
--SPEED 400 \
--ACTIVE 0 \
--TIME_STOP 120 \
--WHISKER_NAMES ALL \
--PITCH 0 \
--AMP_BWD 15 \
--AMP_FWD 35 \
--WHISK_FREQ 8. \
--SAVE_VIDEO 0 \
--SAVE 0 \
--file_video "../output/video_wall.mp4" \
--file_env ../data/3D_data/rat_habitat/drain_pipe.obj \
--dir_out ../output/full_array_peg