
../build/whiskit_gui \
--PRINT 2 \
--DIST 0.07 \
--CPITCH -89 \
--CYAW 0 \
--BLOW 2 \
--DEBUG 0 \
--OBJECT 2 \
--ACTIVE 1 \
--TIME_STOP 0.1 \
--WHISKER_NAMES R \
--PITCH 0 \
--YAW -20 \
--AMP_BWD 15 \
--AMP_FWD 35 \
--WHISK_FREQ 8. \
--SAVE_VIDEO 0 \
--SAVE 1 \
--file_video "../output/video_wall.mp4" \
--dir_out ../output/full_array_wall